### ISSUE TITLE
Not working on 0.18.4 Windows 64b

### ISSUE THREAD

**Issue by dham-eng** [yorikvanhavre/BIM_Workbench#53]
Hello,

upon opening, the BIM workbench throws me this error:

> cannot import name 'IfcProduct'
> Traceback (most recent call last):
>   File "<string>", line 208, in Initialize
>   File "E:\Users\rstecman\AppData\Roaming\FreeCAD\Mod\BIM\archguitools\gui_wall.py", line 37, in <module>
>     import archmake.make_wall as make_wall
>   File "E:\Users\rstecman\AppData\Roaming\FreeCAD\Mod\BIM\archmake\make_wall.py", line 29, in <module>
>     from archobjects.wall import Wall 
>   File "E:\Users\rstecman\AppData\Roaming\FreeCAD\Mod\BIM\archobjects\wall.py", line 35, in <module>
>     from ArchIFC import IfcProduct

It does work on realthunder's ASM3 branch.

OS: Windows 10
Word size of OS: 64-bit
Word size of FreeCAD: 64-bit
Version: 0.18.4 (GitTag)
Build type: Release
Branch: releases/FreeCAD-0-18
Hash: 980bf9060e28555fecd9e3462f68ca74007b70f8
Python version: 3.6.6
Qt version: 5.6.2
Coin version: 4.0.0a
OCC version: 7.3.0
Locale: Portuguese/Brazil (pt_BR)

**Comment by yorikvanhavre** [comment]
Ok I did a better fix in 1c5ec19 I think it should work now! (you'll need to update the BIM workbench)
